name: Build and Deploy Shelter Site

on:
  schedule:
    - cron: '*/360 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Оставляем пока @v4, она уже совместима
      - name: Setup Node.js
        uses: actions/setup-node@v4  # Оставляем пока @v4, она уже совместима
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Fetch data and build site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Обновляем с @v3 на @v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages